version: '1'

services:
  app:
    build:
      context: .
      target: dev
    image: pokerapp
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /poker-payout-calculator/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    environment:
      - DATABASE_URL=postgresql://postgres:example@poker-payout-calculator-db-1:5432/pokerhut-dev-db
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - C:/Users/james/OneDrive/Documents/poker-cashout-project/postgres/:/var/lib/postgresql/data/
