services:
  app:
    build:
      context: .
      target: prod
    image: pokerapp
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:example@poker-payout-calculator-db-1:5432/pokerhut-dev-db  
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: example
      POSTGRES_DB: pokerhut-dev-db
    ports:
      - 5432:5432
    volumes:
      # - /home/ec2-user/volumes/postgres/:/var/lib/postgresql/data/
      - C:/Users/james/OneDrive/Documents/poker-cashout-project/postgres/:/var/lib/postgresql/data/
